version: '3'
services:
  crawler:
    build: 
      context: ./crawler
    container_name: crawler
    # volumes:
    #   - ./everytime/everytime/logs:/everytime/everytime/logs
    #   - ./everytime/everytime/result:/everytime/everytime/result

  command: python3 /project/notice_crawler.py
