version: '3'
services:
  crawler:
    build: 
      context: .
      dockerfile : Dockerfile
    container_name: yoncrawler
    depends_on :
      - mongo
  
  mongo:
    image: mongo:3.6.1
    container_name: mongodb
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod

volumes:
  mongodb:
  mongodb_config:
